server:
  port: 6669


liquibase:
  change-log: classpath:liquibase\master.xml
spring:
  datasource:
    url: jdbc:mysql://www.iamcrawler.cn:3306/spit?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name:  com.mysql.jdbc.Driver

  redis:
    host: localhost
    port: 6379

mybatis:
  type-aliases-package: cn.iamcrawler.domain
  mapper-locations: classpath:cn/iamcrawler/mapper/*Mapper.xml
  type-handlers-package: cn.iamcrawler.mapper.typehandler
  global-config:
    refresh-mapper: true
security:
  oauth2:
    resource:
      filter-order: 3
management:
  security:
    enabled: false
logging:
  level:
    org.springframework: DEBUG
